name: CI

on:
  push:
    branches:
      - main  # You can specify which branches you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
